[general]
live_config_reload = true

[window]
decorations = "None"
opacity = 0.95
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Regular Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Regular Italic" }
size = 12

[selection]
save_to_clipboard = true

[colors.primary]
background = "#151424"

[terminal]
shell = "/usr/bin/nu"
